gui:
  # Customize the look and feel
  theme:
    activeBorderColor:
      - '#88c0d0' # Nord blue
      - bold
    inactiveBorderColor:
      - '#4c566a' # Nord gray
    optionsTextColor:
      - '#88c0d0' # Nord blue
    selectedLineBgColor:
      - '#3b4252' # Nord dark gray
  # Set font options
  fontFamily: "FiraCode Nerd Font"
  fontSize: 8
  lineHeight: 1
  letterSpacing: 0

git:
  # Override default git behavior, e.g., always rebase when pulling
  pull:
    mode: "rebase"
  # Set vim as default editor
  merging:
    editor: "vim"
  commit:
    editor: "vim"
  diffing:
    editor: "vim"

os:
  editPreset: "vim"
